services:
  database:
    image: postgres:17
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
  bot:
    build:
      context: .
      dockerfile: dev.Dockerfile
      args:
        DATABASE_URL: postgres://postgres:postgres@database:5432/postgres
    restart: unless-stopped
    ports:
      - "3000:8000"
    environment:
      DATABASE_URL: postgres://postgres:postgres@database:5432/postgres
    depends_on:
      database:
        condition: service_started
    volumes:
      - "./src:/app/src"